# Generated by Django 3.2.5 on 2021-07-13 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210713_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 16, 5, 5, 715300, tzinfo=utc), max_length=99, unique=True),
            preserve_default=False,
        ),
    ]
