# Generated by Django 3.2.5 on 2021-07-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_post_message_post_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_message',
            new_name='message',
        ),
    ]
