# Generated by Django 3.2.5 on 2021-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, unique=True)),
                ('founder', models.CharField(max_length=20)),
                ('headquator', models.CharField(max_length=50)),
                ('fund_raise', models.CharField(max_length=50)),
                ('working', models.BooleanField(verbose_name=(('working', 'working'), ('close', 'close')))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=99)),
                ('last_name', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('experiance', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
