# Generated by Django 3.2.5 on 2021-07-13 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_company_employee_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Company',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='boards.company'),
            preserve_default=False,
        ),
    ]
